algorithm: bc

data:
  data_path: "/scr/shared/clam/datasets/metaworld/assembly-v2/buffer_assembly-v2.pt"
  env_name: "assembly-v2-goal-observable"  # Exact name of the MetaWorld environment

model:
  hidden_dims: [256, 256]
  learning_rate: 3e-4
  batch_size: 256

training:
  n_epochs: 100

output:
  output_dir: "results/bc_model"
  model_dir_name: "DATASET_NAME_bc_lr${model.learning_rate}_epochs${training.n_epochs}"
  artifact_name: "bc_${data.env_name}_DATASET_NAME"

defaults:
  - common
  - _self_