defaults:
  - _self_

data:
  data_path: "/scr/shared/datasets/robot_pref/can_mh/can_mh.pt"
  segment_length: 32
  use_relative_eef: false
  overwrite: true

image_embedding:
  enabled: false
  model_name: "resnet50"  # Options: resnet50, r3m, radio-g, radio-h, radio-l, radio-b, e-radio
  device: "cuda"
  feature_fmt: "NCHW"
  use_spatial_features: false
  batch_size: 32

dtw:
  enabled: true
  use_relative_eef: false

seed: 42 