name: null
condition_on_task: False
embedding_dim: 256

gaussian_policy: False

# set this if we want to use a pretrained vision model for the encoder
# options: resnet18, ..., lapa, dynamo
embedding_model: null
embedding_model_ckpt: null
embedding_model_id: null
finetune_embedding_model: False

seq_len: 5 # history length
action_horizon: 6 # action pred horizon

action_activation: Tanh
use_only_gripper_state: False

use_separate_gripper: True
arm_loss_weight: 1.0
gripper_loss_weight: 1.0

use_pretrained_embeddings: True
use_custom_cnn: False

input_modalities:
  - states

defaults:
  - _self_
