active_learning:
  enabled: True
  uncertainty_method: "entropy"       # Uncertainty estimation method: "entropy", "disagreement", or "random"
  num_models: 5                       # Number of models to use for uncertainty estimation
  total_queries_per_iteration: 1      # Number of pairs to select in each iteration
  retrain_interval: 1                 # Number of iterations after which to retrain the model
  total_queries: 50                    # Total number of queries to make
  fine_tune: False
  fine_tune_lr: 1e-4

# Reward model architecture
model:
  hidden_dims: [256, 256]
  lr: 1e-4

# Training parameters
training:
  num_epochs: 50
  batch_size: 256
  num_workers: 4
  pin_memory: True