# Hydra config for collecting preferences based on cluster representatives

# Include common settings
defaults:
  - common
  - _self_  # Allow this config to override common settings

# Random seed for reproducibility
random_seed: 42

# Data parameters
data:
  data_path: /scr/aliang80/robot_pref/labeled_datasets/buffer_assembly-v2_balanced.pt
  preprocessed_data: null  # Path to preprocessed data file (used instead of data_path if provided)
  clustering_results: null  # Path to the pickle file with clustering results (REQUIRED)

# Preference collection parameters
preferences:
  n_representatives: 3        # Number of representative segments per cluster
  max_comparisons: null       # Maximum number of pairwise comparisons to perform
  skip_videos: false          # Skip generating videos for preference collection to speed things up
  no_auto_open: false         # Don't automatically open visualization videos
  use_gt_ranking: false       # Use ground truth ranking for augmented preferences instead of user ranking

# Output parameters
output:
  output_dir: results/cluster_preferences  # Directory to save preference data and dataset

# Wandb configuration (for future integration)
wandb:
  use_wandb: false
  tags: ["preferences", "clustering", "trajectories"]
  notes: "Cluster-based preference collection" 