# Hydra config for end-effector segment matching

# Include common settings
defaults:
  - common
  - _self_  # Allow this config to override common settings

# Random seed for reproducibility
random_seed: 42

# Data parameters
data:
  data_paths: 
    - /scr/aliang80/robot_pref/labeled_datasets/buffer_assembly-v2_balanced.pt
    # - "/scr/shared/clam/datasets/metaworld/assembly-v2/buffer_assembly-v2.pt"
    # - "/scr/shared/clam/datasets/metaworld/bin-picking-v2/buffer_bin-picking-v2.pt"
    # - "/scr/shared/clam/datasets/metaworld/peg-insert-side-v2/buffer_peg-insert-side-v2.pt"
  segment_length: 32
  samples_per_dataset: 1000

# Matching parameters
matching:
  top_k: 5
  query_index: null  # If null, a random segment will be chosen as query
  query_indices: []  # List of specific query indices to process, overrides query_index if non-empty
  num_random_queries: 3  # Number of random queries to generate if query_indices is empty

# Visualization settings
visualization:
  use_shared_ranges: true  # Use shared ranges across all visualizations for consistency
  create_videos: true

# Output parameters
output:
  output_dir: "/scr/aliang80/robot_pref/results/eef_matching_results"

# Wandb configuration
wandb:
  use_wandb: false
  tags: ["matching", "end_effector", "trajectories"]
  notes: "End-effector trajectory segment matching" 