# Hydra config for reward model training

# Include common settings
defaults:
  - common
  - _self_  # Allow this config to override common settings

# Data parameters
data:
  data_path: "/scr/shared/clam/datasets/metaworld/assembly-v2/buffer_assembly-v2.pt"
  segment_length: 32
  num_segments: 5000
  num_pairs: 500
  preferences_data_path: null
  
# Model architecture
model:
  hidden_dims: [256, 256]
  lr: 1e-4

# Training parameters
training:
  batch_size: 256
  num_epochs: 100
  num_workers: 4
  pin_memory: true

# Hardware settings
hardware:
  gpu: 0
  use_cpu: false

# Output parameters
output:
  output_dir: results/reward_model
  
# Wandb configuration
wandb:
  tags: ["reward_model", "preference_learning"]
  notes: "Training reward model with Bradley-Terry preference learning"
