defaults:
  - common
  - _self_ 

# Number of models to train with different seeds
num_seeds: 3

# task: pick_up_green_and_slide_pot_right
task: assembly-v2
data_dir: /scr/shared/datasets/robot_pref

data:
  data_path: null  # Path to dataset
  segment_length: 32
  num_segments: 50000
  num_pairs: 1000
  normalize_obs: false
  norm_method: "standard"
  segment_pairs_path: "${data_dir}/${task}/segment_pairs.npy"  # Optional: path to segment pairs file
  segment_indices_path: "${data_dir}/${task}/segment_start_end_indices.npy"  # Optional: path to segment indices file
  # preferences_dir: "${data_dir}/${task}/preferences"  # Optional: directory containing preference JSON files
  preferences_dir: null

  use_images: false
  image_key: "image"
  obs_key: "obs"
  action_key: "action"
  use_image_embeddings: false
  image_embedding_key: "image_embedding"

  preferences_data_path: null

model:
  is_distributional: false  # Set to true for distributional reward model
  hidden_dims: [256, 256]
  image_model: "resnet50"
  embedding_dim: 256
  lr: 0.0003
  
  # Distributional-specific parameters (used when is_distributional=true)
  lambda_weight: 1.0    # Weight for stochastic term in Bradley-Terry loss
  alpha_reg: 0.001        # Weight for regularization loss
  eta: 10.0              # Minimum entropy level for regularization
  num_samples: 5        # Number of samples for approximating expectation

training:
  batch_size: 32
  num_epochs: 100
  num_workers: 4
  pin_memory: true

hardware:
  gpu: 0
  use_cpu: False

output:
  output_dir: results/reward_model
  model_dir_name: "DATASET_NAME_model_seg${data.segment_length}_epochs${training.num_epochs}_pairs${data.num_pairs}_seed${random_seed}_d${model.is_distributional}"
  
wandb:
  use_wandb: false
  project: "robot_pref"
  entity: null
  name: null
  tags: []
  notes: null

seed: 42
