# Hydra config for reward model training with active learning

# Include common settings
defaults:
  - reward_model
  - active_learning  # Include shared active learning parameters
  - _self_  # Allow this config to override common settings

# Override active learning parameters if needed
active_learning:
  enabled: true
  retrain_interval: 1  # Retrain every iteration

# Override data parameters
data:
  data_path: "/scr/shared/clam/datasets/metaworld/assembly-v2/buffer_assembly-v2.pt"
  segment_length: 32
  num_segments: 10000
  num_pairs: 5000

# DTW augmentation parameters
dtw_augmentation:
  enabled: false              # Set to true to enable DTW augmentation
  k_augment: 5                # Number of similar segments to find for each part of a pair
  max_dtw_segments: 5000      # Max segments for computing DTW matrix (null or remove for all).
  
# Hardware settings
hardware:
  gpu: 0
  use_cpu: false

# Output parameters
output:
  output_dir: results/active_reward_model
  # Use fixed placeholder for dataset name that will be replaced in code
  model_dir_name: "DATASET_NAME_active_${active_learning.uncertainty_method}_init${active_learning.initial_size}_max${active_learning.max_queries}_batch${active_learning.batch_size}_aug${dtw_augmentation.enabled}"
  # Artifact name for wandb
  artifact_name: "DATASET_NAME_active_${active_learning.uncertainty_method}_init${active_learning.initial_size}_max${active_learning.max_queries}_aug${dtw_augmentation.enabled}"
  
# Wandb configuration
wandb:
  use_wandb: false
  project: "robot_pref"
  entity: "clvr"
  name: null  # Will be auto-generated
  tags: ["reward_model", "preference_learning", "active_learning"]
  notes: "Active preference learning with uncertainty sampling"


