# Hydra config for sequential preference collection with similarity-based augmentation

# Include common settings
defaults:
  - common
  - _self_  # Allow this config to override common settings

# Random seed for reproducibility
random_seed: 42

# Data parameters
data:
  data_path: "/scr/shared/clam/datasets/metaworld/assembly-v2/buffer_assembly-v2.pt"
  preprocessed_data: null  # Path to preprocessed data file (skips extraction if provided)
  segment_length: 32
  max_segments: 2000
  use_relative_differences: true

# Preference collection parameters
preferences:
  n_queries: 100          # Number of direct preference queries to collect
  k_augment: 5            # Number of similar segments to use for augmentation (for each segment)
  use_ground_truth: true  # Use ground truth rewards for preferences (instead of user input)
  use_dtw_distance: true  # Use DTW distance for segment similarity
  max_dtw_segments: 1000  # Limit segments for DTW calculation to save memory

# Output parameters
output:
  output_dir: "/scr/aliang80/robot_pref/results/sequential_preferences"

# Wandb configuration
wandb:
  use_wandb: false
  tags: ["preferences", "sequential", "similarity", "augmentation"]
  notes: "Sequential preference collection with similarity-based augmentation" 