batch_size: 256
buffer_size: 1_000_000
checkpoints_path: checkpoints
device: cuda
discount: 0.99
env: robomimic_lift
eval_freq: 5000
frac: 1.0
load_model: ''
max_timesteps: 100_000
max_traj_len: 1000
n_episodes: 30
name: BC
normalize: true
seed: 0