batch_size: 256
seq_len: 3
buffer_size: 1_000_000
checkpoints_path: checkpoints
device: "cpu"
discount: 0.99
env: robomimic_lift
eval_freq: 5000
frac: 1.0
load_model: ''
max_timesteps: 150_000
max_traj_len: 1000
n_episodes: 30
name: BC
normalize: false
seed: 0

data_path: null
record_video: false

# wandb
use_wandb: false
wandb:
  project: "robot_pref"
  entity: "clvr"
  name: "bc-${env}-${seed}"