batch_size: 256
buffer_size: 200027
checkpoints_path: null
device: cuda
discount: 0.99
env: halfcheetah-expert-v2
eval_freq: 5000
frac: 1.0
load_model: ''
max_timesteps: 1000000
max_traj_len: 1000
n_episodes: 10
name: BC
normalize: false
seed: 0