name: DT
group: dt-$env-multiseed-v0

# DT
hidden_size: 64
nhead: 2
nlayer: 1
K: 20 # from the paper
target_return: 50.0

discount: 0.99
lr: 3e-4

# reward
use_reward_model: false
trivial_reward: 0 # 1 for zero reward IQL
single_emb: false # GT
eef_rm: false # 3D EEF RM
use_cross: false # DTW augs
dtw_k_augment: 1
wandb:
  name: "dt-${env}-${seed}"

defaults:
- base