name: DT
group: dt-$env-multiseed-v0

# DT
hidden_size: 128
nhead: 4
nlayer: 4
K: 30
target_returns: [30.0, 35.0, 40.0, 45.0, 60.0]
scale: 10.0

discount: 0.99
lr: 3e-4

# reward
use_reward_model: false
trivial_reward: 0 # 1 for zero reward IQL
single_emb: false # GT
eef_rm: false # 3D EEF RM
use_cross: false # DTW augs
dtw_k_augment: 1
wandb:
  name: "dt-${env}-${seed}"
  project: "robot_pref"

defaults:
- reward
- base