# @package _global_
defaults:
  - _self_

# Wandb configuration
wandb:
  project: "robot_pref"
  entity: "clvr"
  user: "hongmm"        # Filter for runs by this user
  max_runs: null          # Maximum number of runs to fetch, null means all
  after_date: "2025-06-12"  # Only include runs created after this date (format: YYYY-MM-DD)

# Output configuration
output:
  output_dir: "analysis"
  plot: True        # Generate comparison plots
  plot_dir: "data_path_plots"

# Other global settings
seed: 42 