actor_lr: 3e-4
batch_size: 256
seq_len: 10
beta: 3.0
buffer_size: 10000000
checkpoints_path: logs/
device: "cuda"
discount: 0.99
env: robomimic_lift
eval_freq: 5000
group: iql-$env-multiseed-v0
iql_deterministic: false
iql_tau: 0.7
load_model: ''
max_timesteps: 150_000
n_episodes: 30
name: IQL
normalize: true
normalize_reward: false
qf_lr: 3e-4
record_video: false
seed: 0
tau: 0.005

vf_lr: 3e-4

use_reward_model: false
trivial_reward: 0 # 1 for zero reward IQL

# Reward model
use_distributional_model: false
use_gt_prefs: false # GT
eef_rm: false # 3D EEF RM
use_dtw_augmentations: false # DTW augs
dtw_k_augment: 1

data_path: "/scr/shared/datasets/robot_pref/lift_panda/lift_panda.hdf5"

# wandb
use_wandb: false
wandb:
  project: "robot_pref"
  entity: "clvr"
  name: "iql-${env}-${seed}"

defaults:
- reward