name: IQL
group: iql-$env-multiseed-v0

# iql
actor_lr: 3e-4
qf_lr: 3e-4
vf_lr: 3e-4
beta: 3.0
tau: 0.005
iql_tau: 0.7

# reward
use_reward_model: false
trivial_reward: 0 # 1 for zero reward IQL

single_emb: false # GT
eef_rm: false # 3D EEF RM
use_cross: false # DTW augs
dtw_k_augment: 1

wandb:
  name: "iql-${env}-${seed}"
  project: "robot_pref"

defaults:
- reward
- base