device: cuda
env: metaworld-button-press-v2
seed: 0
checkpoints_path: logs/
load_model: null
# preference
feedback_num: 100 # Number of human preferences from the source dataset to use for augmentation
test_feedback_num: 100 # Number of human preferences from the target dataset to use for testing

data_quality: 5.0
segment_size: 32
normalize: true
threshold: 0.5
data_aug: none
q_budget: 1
feedback_type: RLT
model_type: BT
noise: 0.0
human: false
# MLP
epochs: 1000
batch_size: 256
activation: tanh
lr: 1e-3
hidden_sizes: 128
ensemble_num: 3
ensemble_method: mean

data_path: "/scr/shared/datasets/robot_pref/lift_panda/lift_panda.hdf5"
target_data_path: "/scr/shared/datasets/robot_pref/lift_sawyer/lift_sawyer.hdf5"
