
# preference
feedback_num: 500 # Number of human preferences from the source dataset to use for augmentation
test_feedback_num: 100 # Number of human preferences from the target dataset to use for testing

# general
data_quality: 5.0
segment_size: 32
normalize: true
threshold: 0.5
data_aug: none
q_budget: 1
feedback_type: RLT
model_type: BT
noise: 0.0
human: true
epochs: 6000
activation: none
lr: 1e-4
hidden_sizes: 128
dropout: 0.3
n_layers: 1
ensemble_num: 3 # not using active querying for now
ensemble_method: mean
use_distributional_model: false # Use distributional reward model

# methods
single_emb: false # GT
use_cross: false # DTW X-augs
eef_rm: false # 3D EEF RM
eef_rm_2d: false # 3D EEF w/ 2D goal position RM

# cross preferences
use_goal_pos: false # add goal position to the dtw segments
use_relative_eef: false
dtw_k_augment: 1

# data
data_path: ""
cross_data_path: ""

wandb:
  name: "RM-${env}-${seed}"
  project: "Reward Learning"

defaults:
- base