activation: tanh
actor_dropout: null
actor_lr: 0.0003
batch_size: 256
beta: 3.0
buffer_size: 300000
checkpoints_path: checkpoints/IQL/metaworld_sweep-v2/data_1.0/fn_500/qb_1/ft_RLT/m_BT/n_0.0/e_300/seed_10
data_aug: none
data_quality: 1.0
device: cuda
discount: 0.99
ensemble_method: mean
ensemble_num: 3
entity: clvr
env: metaworld_sweep-v2
epochs: 300
eval_freq: 5000
feedback_num: 500
feedback_type: RLT
group: metaworld_sweep-v2_data_1.0_fn_500_qb_1_ft_RLT_m_BT_n_0.0_e_300_trivial_0
hidden_sizes: 128
human: false
iql_deterministic: false
iql_tau: 0.7
load_model: ''
lr: 0.001
max_timesteps: 250000
model_type: BT
n_episodes: 50
name: seed_10_07f2a2d2
noise: 0.0
normalize: true
normalize_reward: true
project: robot_pref
q_budget: 1
qf_lr: 0.0003
seed: 10
segment_size: 25
tau: 0.005
threshold: 0.5
trivial_reward: 0
use_reward_model: true
vf_lr: 0.0003
